[package]
name = "raster_drone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "raster_drone"
crate-type = ["cdylib"]

[dependencies]
clap = "4.5.48"
image = "0.25.8"
pyo3 = "0.23.3"
